server:
  port: 20000

spring:
  application:
    name: aop-demo
  redis:
    port: 6379
    host: 192.168.1.200
    password: wsxs.130
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: 1ms
        max-idle: 8
        min-idle: 0


# 下游系统开关
downstream:
  system:
    switch:
      shipout: true
      koda: false
